version: 2.1
jobs:
  build_and_publish:
    docker:
      - image: cimg/node:24.16
    working_directory: ~/repo
    steps:
      - checkout
      - run: npm ci
      - run: npm run test:unit
      - run: npx redbox-dev-tools check
      - run:
          name: Authenticate with NPM
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/repo/.npmrc
      - run:
          name: Publish package
          command: npm publish --access public

workflows:
  publish:
    jobs:
      - build_and_publish:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
